[ASSIST-903]: Default Folders for All AI Users
canyongbs/assistbycanyongbs pull request #289
Opened 2023-11-21 01:56 UTC by dgoetzit

### Ticket(s) or GitHub Issue

https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/903/

### Technical Description

This PR introduces default chat folders for the AI Assistant, created on each user's initial acceptance of the terms and conditions when using the Assistant.

### Types of changes

- [x] New feature (non-breaking change which adds functionality)

### Screenshots (if appropriate)

### Any deployment steps required?

- [x] No

_______________________________________________

## Before contributing and submitting this PR, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/canyongbs/assistbycanyongbs/blob/main/README.md#contributing).
* [x] Title the PR with the ticket/issue number and a short description of the changes made. Or if no ticket/issue exists, title the PR with a short description of the changes made
* [x] Linked a relevant ticket or issue or describe the issue/feature which this PR resolves/implements.
* [x] Resolved all conflicts, if any.
* [x] Rebased your branch PR on top of the latest upstream `develop` branch.

2023-11-21 14:46 UTC, Orrison requested changes
Looks good, but looks like some tests are currently failing.

2023-11-21 14:51 UTC, mxm1070 commented
I'm not sure about the intent of the ticket, but should this be configureable by the Admins? Also if the list of folders changes should it rerun?

2023-11-21 18:30 UTC, mxm1070 commented on app/Models/User.php
> +        return (bool) $this->default_assistant_chat_folders_created;
Maybe add this to the $casts array as a boolean?

2023-11-21 21:04 UTC, mxm1070 approved these changes

2023-11-22 13:53 UTC, Orrison approved these changes

2023-11-22 13:53 UTC, merged